nginx:
  image: nginx
  ports:
    - "80:80"
  links:
    - fabric
  volumes:
    - ./nginx:/etc/nginx/conf.d
  restart: always

data:
  image: busybox
  volumes:
    - ./persistent/data:/data
    - ./persistent/postgresql/var/lib:/var/lib/postgresql/data
    - ./persistent/src:/src
  entrypoint: /bin/echo

postgres:
  image: postgres
  volumes_from:
    - data
  restart: always

fabric:
  image: leominov/fabric-bolt
  links:
    - postgres
  volumes:
    - ./docker-entrypoint-init.d:/docker-entrypoint-init.d
    - ./fabric-bolt:/root/.fabric-bolt
    - ./ssh:/root/.ssh
  volumes_from:
    - data
  env_file:
    - private-data/environment.sh
  restart: always
