nginx:
  image: nginx
  ports:
    - "80:80"
  links:
    - fabric
  volumes:
    - ./nginx:/etc/nginx/conf.d
  restart: always

data:
  image: busybox
  volumes:
    - /data
    - /var/lib/postgresql/data
  entrypoint: /bin/echo

postgres:
  image: postgres
  volumes_from:
    - data
  restart: always

fabric:
  image: leominov/fabric-bolt
  links:
    - postgres
  volumes:
    - ./fabric-bolt:/root/.fabric-bolt
    - ./ssh:/root/.ssh
  volumes_from:
    - data
  command: /src/run
  env_file:
    - private-data/environment.sh
  restart: always
